import { Button, VerticalBox, ListView,HorizontalBox ,Slider, StandardListView, ProgressIndicator } from "std-widgets.slint";


import {SystemService, DAWService} from "./utils.slint";
import {FilePlayer} from "./file-player.slint";
import {DAW} from "./daw.slint";

//enum for the UI main parameters



// Popup for the user to choose a song from a list of files inside a directory defined backend





// main component 
export component AppWindow inherits Window {

	preferred-width: SystemService.global_width_length;
	preferred-height: SystemService.global_height_length;

	min-width: SystemService.global_width_length; 
	min-height: SystemService.global_height_length;
	
	// TO PLAY FILES 
	callback request-load-popup();
	callback request-load-file();
	callback request-fetch-directory();
	callback request-user-selected-file(int);
	callback request-import-file();

	callback request-progress-bar() ; 

	callback request-play-pause();
	callback request-stop();
	callback request-change-volume(float);

	callback request-close-app(); 

	in property <[StandardListViewItem]> file_model;
	in property <string> selected_file : "File selected : None";
	in property <string> selected_file_title : "Media Title will be displayed here";
	

	in property <float> progress_indicator : 0.0;
	in property <bool> is_playing : false;


	// DAW 

	callback request-add-sinwave();
	callback request-singraph(float, float, string);
	
	in property <image> singraph;
	in-out property <string> wave_selected;

	// timer for the progress bar 
	timer := Timer {
		interval: 100ms; 
		running: is_playing; 
		triggered => {
			root.request-progress-bar();
		}
	}

	background: #8c9aac;
	
	MenuBar {
		Menu{
			title:@tr("File"); 
			
			MenuItem {
				title:@tr("Open from project"); 
				activated => {}
			}
			MenuItem {
				title:@tr("Import from PC"); 
			}
		}
	}
	HorizontalLayout {
		DAW{

			from-root-request-add-sinwave => {root.request-add-sinwave()}
			from-root-request-singraph => {
				root.request-singraph(DAWService.f_singraph_width, DAWService.f_singraph_height, DAWService.selected_wave_str)
			}

			singraph: singraph;
		}
		/*
		FilePlayer {
			from-root-request-fetch-directory => {root.request-fetch-directory()}
			from-root-request-load-file => {root.request-load-file()}
			from-root-request-user-selected-file(index) => {root.request-user-selected-file(index)}
			from-root-request-import-file => {root.request-import-file()}
			from-root-request-stop => {root.request-stop()}
			from-root-request-play-pause => {root.request-play-pause()}
			from-root-request-change-volume(value) => {root.request-change-volume(value)}
			from-root-request-close-app() => {root.request-close-app()}

			file_model: file_model;
			selected_file: selected_file;
			selected_file_title: selected_file_title; 
			progress_indicator: progress_indicator;
			is_playing: is_playing;
		}
		*/

	}
}


export {DAWService, SystemService}
