import { Button, VerticalBox, ListView,HorizontalBox ,Slider, StandardListView, ProgressIndicator } from "std-widgets.slint";


import {DAWService, SystemService} from "./utils.slint";

component Effects {
	callback from-daw-request-add-sinwave();
	callback from-daw-request-singraph(float, float, string);

	in-out property <string> wave_selected :"No wave selected";
	in property <string> wave_picture : "default";

	in property <image> singraph; 

	pure function get-button-text() -> string {
		return "Add" + wave_selected;
	}

	VerticalLayout {

		// Add wave or effects
		Rectangle {

			border-width: 4pt;
			background: DAWService.bg_main_color;
			clip: true;

			VerticalBox {
				x: 0; 
				y:0;
				height: DAWService.wave_box_height; 
				width: DAWService.wave_box_width;
				// Add wave
				Rectangle {

					height: DAWService.select_wave_height; 
					width: DAWService.select_wave_width;

					border_width: 2pt;
					border-radius: 10px;
					border-color: DAWService.border-color;

					wave_popup := PopupWindow {
						Rectangle {
							background: DAWService.bg_secondary_color;

							border_width: 2pt;
							border-radius: 10px;
							border-color: DAWService.border-color;
									
							Rectangle {
								Text {
									text: "SinWave"; 
								}	

								TouchArea {
									clicked => {
										DAWService.selected_wave_str = "SinWave";	
										from-daw-request-singraph(DAWService.f_singraph_width, DAWService.f_singraph_height,DAWService.selected_wave_str);
									}
								}
							}
						}

						x: 20px; 
						y: 20px;
						width: DAWService.wave_popup_width;
						height: DAWService.wave_popup_height;

					}

					TouchArea {
        		clicked => { wave_popup.show(); }
					}

					Text {
						height: 20%;
						text: "WaveType"; 
					}
					
				}

				VerticalBox {
					HorizontalBox {
						Text {
							height: 20%; 
							width: 50%;

							vertical-alignment: center;
							horizontal-alignment: right;

							text:"Oscillator";
						
						}

						Text {
							height: 20%; 
							width: 50%;
							vertical-alignment: center;
							horizontal-alignment: left; 

							text: "for : " + root.wave_selected; 
						}
					}
					Rectangle {
						border_width: 2pt;
						border-radius: 10px;
						border-color: DAWService.border-color;
						height: DAWService.singraph_height; 
						width: DAWService.singraph_width;
						clip: true;
						background: DAWService.bg_secondary_color;
						Image {
							source: singraph;
						}
					}	
				}
			

				// Final rectangle 
				Rectangle {
					height: parent.height * 0.2;				
					background: DAWService.bg_secondary_color;
					Button {
						text: get-button-text(); 
						clicked => {from-daw-request-add-sinwave()}
					}
				}
				
			}
		}	
	}

}

component PlaylistBlock {
    VerticalLayout {
			
		}
}

component PlaylistInput {
	HorizontalBox {
		// 
		Rectangle {
			width: 10%; 
			height: 100%;

			Text {
				horizontal-alignment: left;
				text: "Input " + DAWService.block_cpt; 
			}
		}
	}
}

component Playlist {

	init => {
		DAWService.block_cpt += 1; 
	}
	
	VerticalLayout {
		PlaylistInput {
		}
		PlaylistInput {}
	}	

}

component DAW{
	callback from-root-request-add-sinwave();
	callback from-root-request-singraph(float, float, string);

	in property <image> singraph;
	in-out property <string> wave_selected;

	VerticalLayout {
		height: DAWService.main_layout_height; 
		width: DAWService.main_layout_width;
		x: 0; 
		y: 0 ;

		Effects {
			height: DAWService.effects_box_height; 
			width: DAWService.effects_box_width;

			from-daw-request-add-sinwave => {from-root-request-add-sinwave()}
			from-daw-request-singraph => {
				from-root-request-singraph(DAWService.f_singraph_width, DAWService.f_singraph_height, DAWService.selected_wave_str)
			}
		
			wave_selected: wave_selected; 
			singraph: singraph; 
		}

		Playlist {

		}
	}
}

export {DAW}
