import { 
Button, 
VerticalBox, 
ListView,
HorizontalBox ,
Slider, 
StandardListView,
ProgressIndicator, ComboBox,
} from "std-widgets.slint";




import {DAWService, SystemService, DAWLogic} from "./utils.slint";

component Effects {
	callback from-daw-request-add-sinwave();

	in-out property <string> wave_selected :"No wave selected";
	in property <string> wave_picture : "default";

	in property <string> button_str : "Select a wave";

	in property <image> singraph; 

	VerticalLayout {

		// Add wave or effects
		Rectangle {

			border-width: 4pt;
			border-color: DAWService.border-color; 

			background: DAWService.bg_main_color;
			clip: true;

			VerticalBox {
				x: 0; 
				y: 0;
				height: DAWService.wave_box_height; 
				width: DAWService.wave_box_width;
				// Add wave
				Rectangle {

					height: DAWService.select_wave_height; 
					width: DAWService.select_wave_width;

					border_width: 2pt;
					border-radius: 10px;
					border-color: DAWService.border-color;

					wave_popup := PopupWindow {
						Rectangle {
							background: DAWService.bg_secondary_color;

							border_width: 2pt;
							border-radius: 10px;
							border-color: DAWService.border-color;
									
							Rectangle {
								Text {
									text: "SinWave"; 
								}	

								TouchArea {
									clicked => {
										DAWService.selected_wave_str = "SinWave";
										DAWService.add_wave_button_str = "Add SinWave";
										DAWLogic.request-singraph(DAWService.f_singraph_width, DAWService.f_singraph_height,DAWService.selected_wave_str);
									}
								}
							}
						}

						x: 20px; 
						y: 20px;
						width: DAWService.wave_popup_width;
						height: DAWService.wave_popup_height;

					}

					TouchArea {
        		clicked => { wave_popup.show(); }
					}

					Text {
						height: 20%;
						text: "WaveType"; 
					}
					
				}

				VerticalBox {
					HorizontalBox {
						Text {
							height: 20%; 
							width: 50%;

							vertical-alignment: center;
							horizontal-alignment: right;

							text:"Oscillator";
						
						}

						Text {
							height: 20%; 
							width: 50%;
							vertical-alignment: center;
							horizontal-alignment: left; 

							text: "for : " + root.wave_selected; 
						}
					}
					Rectangle {
						border_width: 2pt;
						border-radius: 10px;
						border-color: DAWService.border-color;
						height: DAWService.singraph_height; 
						width: DAWService.singraph_width;
						clip: true;
						background: DAWService.bg_secondary_color;
						Image {
							source: singraph;
						}
					}	
				}
			

				// Final rectangle 
				Rectangle {
					height: parent.height * 0.2;				
					background: DAWService.bg_secondary_color;

					HorizontalBox {
						Button {
							text: DAWService.add_wave_button_str; 
							clicked => {DAWLogic.request-add-sinwave-to-playlist()}
						}
						
						ComboBox {
							width: 50%; 
							height: 100%;
							//use callback to fill that 
							model: [1,2,3,4,5];
							current-value: "For input";

							selected(current-value) => {}
						}	
					}
				}
				
			}
		}	
	}

}

component PlaylistBar{

	in property <string> input_name: "none";

    VerticalLayout {
			Rectangle {
				Text {
					vertical-alignment: center; 
					text: input_name;  
				}
			}
		}
}

component PlaylistInput {

	in property <int> input_nb;

	HorizontalBox {

		Rectangle {
				
			width: DAWService.input_box_width;
			height: DAWService.input_box_height;

			border-color: red;
			border-width: 2pt;


			HorizontalBox {
				Rectangle {
					width: 10%; 
					height: 100%;

					border-width: 4pt; 
					border-color: black; 

					Text {
						horizontal-alignment: center;
						text: "Input " + input_nb; 
					}
				} 
				
				VerticalBox {
					width: 15%; 
					height: 20%;
					PlaylistBar {

					}			
				
				}
			}

		}
	}
}

component Playlist {
	
	VerticalBox {

		height: DAWService.playlist_box_height; 
		width: DAWService.playlist_box_width; 
		
		x: 0; 
		Rectangle {
			clip: true;
			width: 100%; 
			height: 100%;

			border-color: DAWService.border-color; 
			border-width: 6pt; 

			for i in 10 :
				PlaylistInput{
					y: DAWService.input_box_height * i;
					input_nb: i+1;
				}	
		}
		
	}	

}

component DAW{

	in property <image> singraph;
	in-out property <string> wave_selected;

	VerticalLayout {
		height: DAWService.main_layout_height; 
		width: DAWService.main_layout_width;
		x: 0; 
		y: 0 ;

		Effects {
			height: DAWService.effects_box_height; 
			width: DAWService.effects_box_width;
		
			wave_selected: wave_selected; 
			singraph: singraph; 
		}

		Playlist {

		}
	}
}

export {DAW}
