import { Button, VerticalBox, ListView,HorizontalBox ,Slider, StandardListView, ProgressIndicator } from "std-widgets.slint";

import {SystemService} from "./utils.slint";

component SelectFilePopup inherits PopupWindow{

	callback from-load-request-user-selected-file(int);
	callback from-load-request-load-file();

	in property <[StandardListViewItem]> file_model;
	in property <string> selected_file;

	close-policy: no-auto-close; 
	height: SystemService.global_height_length * 0.8; 
	width: SystemService.global_width_length * 0.8; 
	x: (SystemService.global_width_length - root.width) / 2; 
	y: (SystemService.global_height_length - root.height) / 2;

	Rectangle { 
		background: grey;

		VerticalLayout {
				StandardListView {
					model: root.file_model;
					current-item-changed(current-item) => {from-load-request-user-selected-file(current-item)}
				}

				Text {
					text: root.selected_file;
				}
			HorizontalBox {
				Button {
					text: "Close";
					clicked => root.close(); 
				}
				Button {
					text: "Confirm";
					clicked => {
						root.from-load-request-load-file();
						root.close();
					}
				}
			}
		}
	}

}

component LoadFile inherits Rectangle {
	
	callback from-app-request-load-file();
	callback from-app-request-fetch-directory();
	callback from-app-request-user-selected-file(int);

	callback from-app-request-import-file();
	in property <[StandardListViewItem]> file_model;
	in property <string> selected_file;

	popup_select := SelectFilePopup{
		from-load-request-user-selected-file(index) => {root.from-app-request-user-selected-file(index)}
		from-load-request-load-file => {root.from-app-request-load-file()}
		file_model: file_model;
		selected_file: selected_file;
	}
 
	VerticalBox {
		Rectangle {
			height: 15%;
			Text {
				text: "Supported formats: mp3, wav & ogg";
				vertical-alignment: center; 

			}
		}

		Button {
			text: "Play from project folder..."; 
			clicked => {
				root.from-app-request-fetch-directory();
				popup_select.show();
			}
		}

		Button {
			text: "Import file from your home directory..."; 
			clicked => {
				root.from-app-request-import-file();	
			} 
		}
	}

}

component FilePlayer{

	callback from-root-request-load-file(); 
	callback from-root-request-fetch-directory(); 
	callback from-root-request-user-selected-file(int); 
	callback from-root-request-import-file(); 

	callback from-root-request-stop(); 
	callback from-root-request-play-pause();
		
	callback from-root-request-change-volume(float);

	callback from-root-request-close-app();

	in property <[StandardListViewItem]> file_model;
	in property <string> selected_file : "File selected : None";
	in property <string> selected_file_title : "Media Title will be displayed here";

	in property <float> progress_indicator : 0.0;
	in property <bool> is_playing : false;


	VerticalLayout {
		HorizontalLayout {
			LoadFile {
				from-app-request-load-file => {root.from-root-request-load-file()}
				from-app-request-fetch-directory => {root.from-root-request-fetch-directory()}
				from-app-request-user-selected-file(index) => {root.from-root-request-user-selected-file(index)}
				from-app-request-import-file => {root.from-root-request-import-file()}
				file_model: file_model;
				selected_file: selected_file;
			}

					Text {
						wrap: word-wrap; 
							text: root.selected_file_title;
							horizontal-alignment: center;
							vertical-alignment: center; 
							font-size: 20px;

					}
			}
			VerticalBox {
				HorizontalBox {
					Button {
						text: "Stop"; 
						clicked =>
							root.from-root-request-stop();
					}
					Button {
						text: "Play/Pause";
						clicked => {
							root.from-root-request-play-pause();
						}
					}
				}
				Rectangle {
					height:10%;
					Text{
						text: "Progress Bar";
						horizontal-alignment: center;
						vertical-alignment: center;
					}
				}
				ProgressIndicator {
					width: 90%; 
					height: 40px;

					progress: root.progress_indicator; 
					
				}

			}

			HorizontalLayout {
				height: 15%;
				Text {
					text: "Volume slider :";
					vertical-alignment: center;
				}
				Slider {
					minimum: 0;
					maximum: 100;
					value: 50; 
					released(value) => {
						debug("(UI) : volume slider value changed : ", value);
						root.from-root-request-change-volume(value);
					}
				}
			}	
	}

}


export {FilePlayer}
